package com.freight.model;

import javax.persistence.*;

import com.freight.common.EntityBase;

/**
 * Auto-generated by:
 * org.freight.AdempiereCustomizer
 */
@Entity
@Table(name="ad_menu_v")
public class ADMenuV extends EntityBase {
	private static final long serialVersionUID = 1L;
	private String action;
	private Integer aDMenuID;
	private Integer aDTreeID;
	private Integer aDWindowID;
	private String description;
	private String formPrototype;
	private String image;
	private String menuItem;
	private Integer seqNo;
	private String treeName;
	private String treeType;

	public ADMenuV() {
	}

	public ADMenuV(Integer adMenuId) {
		this.aDMenuID = adMenuId;
	}

	@Basic
	@Column(length=1)
	public String getAction() {
		return action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Id
	@Column(name="ad_menu_id", columnDefinition="INT")
	public Integer getADMenuID() {
		return aDMenuID;
	}

	public void setADMenuID(Integer adMenuId) {
		this.aDMenuID = adMenuId;
	}

	@Basic
	@Column(name="ad_tree_id", columnDefinition="INT", nullable=false)
	public Integer getADTreeID() {
		return aDTreeID;
	}

	public void setADTreeID(Integer adTreeId) {
		this.aDTreeID = adTreeId;
	}

	@Basic
	@Column(name="ad_window_id", columnDefinition="INT")
	public Integer getADWindowID() {
		return aDWindowID;
	}

	public void setADWindowID(Integer adWindowId) {
		this.aDWindowID = adWindowId;
	}

	@Basic
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Basic
	@Column(name="form_prototype", length=60)
	public String getFormPrototype() {
		return formPrototype;
	}

	public void setFormPrototype(String formPrototype) {
		this.formPrototype = formPrototype;
	}

	@Basic
	@Column(length=60)
	public String getImage() {
		return image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Basic
	@Column(name="menu_item", nullable=false, length=60)
	public String getMenuItem() {
		return menuItem;
	}

	public void setMenuItem(String menuItem) {
		this.menuItem = menuItem;
	}

	@Basic
	@Column(name="seq_no", columnDefinition="INT", nullable=false)
	public Integer getSeqNo() {
		return seqNo;
	}

	public void setSeqNo(Integer seqNo) {
		this.seqNo = seqNo;
	}

	@Basic
	@Column(name="tree_name", length=60)
	public String getTreeName() {
		return treeName;
	}

	public void setTreeName(String treeName) {
		this.treeName = treeName;
	}

	@Basic
	@Column(name="tree_type", length=2)
	public String getTreeType() {
		return treeType;
	}

	public void setTreeType(String treeType) {
		this.treeType = treeType;
	}
}