package com.freight.model;

import javax.persistence.*;

import com.freight.common.EntityBase;

/**
 * Auto-generated by: org.freight.AdempiereCustomizer
 */
@Entity
@Table(name = "ad_ref_table")
public class ADRefTable extends EntityBase {
	private static final long serialVersionUID = 1L;
	private Integer aDClientID;
	private Integer aDOrgID;
	private Integer aDReferenceID;
	private Integer aDTableID;
	private Boolean active;
	private String aDDisplay;
	private String aDValue;
	private Integer adWindowId;
	private String created;
	private Integer createdBy;
	private String queryName;
	private String updated;
	private Integer updatedBy;
	private boolean view;

	public ADRefTable() {
	}

	public ADRefTable(Integer aDReferenceID) {
		this.aDReferenceID = aDReferenceID;
	}

	@Basic
	@Column(name = "ad_client_id", columnDefinition = "INT", nullable = false)
	public Integer getADClientID() {
		return aDClientID;
	}

	public void setADClientID(Integer aDClientID) {
		this.aDClientID = aDClientID;
	}

	@Basic
	@Column(name = "ad_org_id", columnDefinition = "INT", nullable = false)
	public Integer getADOrgID() {
		return aDOrgID;
	}

	public void setADOrgID(Integer aDOrgID) {
		this.aDOrgID = aDOrgID;
	}

	@Id
	@Column(name = "ad_reference_id", columnDefinition = "INT")
	public Integer getADReferenceID() {
		return aDReferenceID;
	}

	public void setADReferenceID(Integer aDReferenceID) {
		this.aDReferenceID = aDReferenceID;
	}

	@Basic
	@Column(name = "ad_table_id", columnDefinition = "INT", nullable = false)
	public Integer getADTableID() {
		return aDTableID;
	}

	public void setADTableID(Integer aDTableID) {
		this.aDTableID = aDTableID;
	}

	@Basic
	@Column(nullable = false)
	public Boolean isActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Basic
	@Column(name = "ad_display", nullable = false, length = 60)
	public String getADDisplay() {
		return aDDisplay;
	}

	public void setADDisplay(String adDisplay) {
		this.aDDisplay = adDisplay;
	}

	@Basic
	@Column(name = "ad_value", nullable = false, length = 60)
	public String getADValue() {
		return aDValue;
	}

	public void setADValue(String adValue) {
		this.aDValue = adValue;
	}

	@Basic
	@Column(name = "ad_window_id", columnDefinition = "INT")
	public Integer getAdWindowId() {
		return adWindowId;
	}

	public void setAdWindowId(Integer adWindowId) {
		this.adWindowId = adWindowId;
	}

	@Basic
	@Column(nullable = false)
	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	@Basic
	@Column(name = "created_by", columnDefinition = "INT", nullable = false)
	public Integer getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Basic
	@Column(name = "query_name", length = 60)
	public String getQueryName() {
		return queryName;
	}

	public void setQueryName(String queryName) {
		this.queryName = queryName;
	}

	@Basic
	public String getUpdated() {
		return updated;
	}

	public void setUpdated(String updated) {
		this.updated = updated;
	}

	@Basic
	@Column(name = "updated_by", columnDefinition = "INT")
	public Integer getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	public boolean isView() {
		return view;
	}

	public void setView(boolean view) {
		this.view = view;
	}

}