package com.freight.model;

import javax.persistence.*;

import com.freight.common.EntityBase;

/**
 * Auto-generated by:
 * org.freight.AdempiereCustomizer
 */
@Entity
@Table(name="ad_ref_list_v")
public class ADRefListV extends EntityBase {
	private static final long serialVersionUID = 1L;
	private Integer aDRefListID;
	private String columnName;
	private String display;
	private String refName;
	private String value;

	public ADRefListV() {
	}

	public ADRefListV(Integer aDRefListID) {
		this.aDRefListID = aDRefListID;
	}

	@Id
	@Column(name="ad_ref_list_id", columnDefinition="INT")
	public Integer getADRefListID() {
		return aDRefListID;
	}

	public void setADRefListID(Integer aDRefListID) {
		this.aDRefListID = aDRefListID;
	}

	@Basic
	@Column(name="column_name", length=45)
	public String getColumnName() {
		return columnName;
	}

	public void setColumnName(String columnName) {
		this.columnName = columnName;
	}

	@Basic
	@Column(nullable=false, length=60)
	public String getDisplay() {
		return display;
	}

	public void setDisplay(String display) {
		this.display = display;
	}

	@Basic
	@Column(name="ref_name", nullable=false, length=45)
	public String getRefName() {
		return refName;
	}

	public void setRefName(String refName) {
		this.refName = refName;
	}

	@Basic
	@Column(nullable=false, length=20)
	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}
}