package com.freight.model;

import java.util.List;

import javax.persistence.*;

import com.freight.common.EntityBase;

/**
 * Auto-generated by: org.freight.AdempiereCustomizer
 */
@Entity
@Table(name = "ad_tree")
public class ADTree extends EntityBase {
	private static final long serialVersionUID = 1L;
	private Integer aDClientID;
	private Integer aDOrgID;
	private Boolean active;
	private Integer aDTreeID;
	private String created;
	private Integer createdby;
	private String description;
	private String iconClass;
	private String name;
	private String treeType;
	private String updated;
	private Integer updatedby;
	private List<ADMenu> aDMenus;

	public ADTree() {
	}

	public ADTree(Integer aDTreeID) {
		this.aDTreeID = aDTreeID;
	}

	@Basic
	@Column(name = "AD_CLIENT_ID", columnDefinition = "INT", nullable = false)
	public Integer getADClientID() {
		return aDClientID;
	}

	public void setADClientID(Integer aDClientID) {
		this.aDClientID = aDClientID;
	}

	@Basic
	@Column(name = "AD_ORG_ID", columnDefinition = "INT", nullable = false)
	public Integer getADOrgID() {
		return aDOrgID;
	}

	public void setADOrgID(Integer aDOrgID) {
		this.aDOrgID = aDOrgID;
	}

	@Basic
	@Column(nullable = false)
	public Boolean isActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Id
	@Column(name = "AD_TREE_ID", columnDefinition = "INT")
	public Integer getADTreeID() {
		return aDTreeID;
	}

	public void setADTreeID(Integer aDTreeID) {
		this.aDTreeID = aDTreeID;
	}

	@Basic
	@Column(columnDefinition = "TIMESTAMP", nullable = false)
	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	@Basic
	@Column(name ="created_by", columnDefinition = "INT", nullable = false)
	public Integer getCreatedby() {
		return createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	@Basic
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Basic
	@Column(name = "icon_class", length = 60)
	public String getIconClass() {
		return iconClass;
	}

	public void setIconClass(String iconClass) {
		this.iconClass = iconClass;
	}

	@Basic
	@Column(nullable = false, length = 60)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Basic
	@Column(nullable = false, length = 2)
	public String getTreeType() {
		return treeType;
	}

	public void setTreeType(String treetype) {
		this.treeType = treetype;
	}

	@Basic
	@Column(columnDefinition = "TIMESTAMP", nullable = false)
	public String getUpdated() {
		return updated;
	}

	public void setUpdated(String updated) {
		this.updated = updated;
	}

	@Basic
	@Column(name ="updated_by", columnDefinition = "INT", nullable = false)
	public Integer getUpdatedby() {
		return updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}

	// bi-directional many-to-one association to ADMenu
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tree")
	public List<ADMenu> getADMenus() {
		return this.aDMenus;
	}

	public void setADMenus(List<ADMenu> aDMenus) {
		this.aDMenus = aDMenus;
	}

	public ADMenu addADMenu(ADMenu aDMenu) {
		getADMenus().add(aDMenu);
		aDMenu.setTree(this);

		return aDMenu;
	}

	public ADMenu removeADMenu(ADMenu aDMenu) {
		getADMenus().remove(aDMenu);
		aDMenu.setTree(null);

		return aDMenu;
	}
}