package com.freight.model;

import java.math.*;
import javax.persistence.*;

import com.freight.common.EntityBase;

/**
 * Auto-generated by:
 * org.freight.AdempiereCustomizer
 */
@Entity
@Table(name="c_bpartner")
public class CBPartner extends EntityBase {
	private static final long serialVersionUID = 1L;
	private Integer aDClientID;
	private Integer aDOrgID;
	private BigDecimal accoutBalance;
	private Boolean active;
	private String addr;
	private Integer cBPartnerID;
	private Integer cCityID;
	private Boolean consignee;
	private Boolean consignor;
	private String contractNo;
	private String created;
	private Integer createdBy;
	private BigDecimal creditBalance;
	private Integer creditQuota;
	private String dateFirstsale;
	private String dockAddr;
	private String fax;
	private String importantNote;
	private Integer industryType;
	private String mobile;
	private String name;
	private String orgName;
	private Integer payMethod;
	private String phone;
	private Integer salesrepUserID;
	private Boolean shipper;
	private String updated;
	private Integer updatedBy;
	private String zip;

	public CBPartner() {
	}

	public CBPartner(Integer cBpartnerID) {
		this.cBPartnerID = cBpartnerID;
	}

	@Basic
	@Column(name="ad_client_id", columnDefinition="INT", nullable=false)
	public Integer getADClientID() {
		return aDClientID;
	}

	public void setADClientID(Integer aDClientID) {
		this.aDClientID = aDClientID;
	}

	@Basic
	@Column(name="ad_org_id", columnDefinition="INT", nullable=false)
	public Integer getADOrgID() {
		return aDOrgID;
	}

	public void setADOrgID(Integer aDOrgID) {
		this.aDOrgID = aDOrgID;
	}

	@Basic
	@Column(name="accout_balance", nullable=false)
	public BigDecimal getAccoutBalance() {
		return accoutBalance;
	}

	public void setAccoutBalance(BigDecimal accoutBalance) {
		this.accoutBalance = accoutBalance;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Basic
	@Column(nullable=false, length=80)
	public String getAddr() {
		return addr;
	}

	public void setAddr(String addr) {
		this.addr = addr;
	}

	@Id
	@Column(name="c_bpartner_id", columnDefinition="INT")
	@TableGenerator(name = "PkGen_111", table = "ad_sequence", pkColumnName = "name", pkColumnValue = "C_BPartner", valueColumnName = "currentnextsys", allocationSize = 1 )
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "PkGen_111")
	public Integer getCBPartnerID() {
		return cBPartnerID;
	}

	public void setCBPartnerID(Integer cBpartnerID) {
		this.cBPartnerID = cBpartnerID;
	}

	@Basic
	@Column(name="c_city_id", columnDefinition="INT", nullable=false)
	public Integer getCCityID() {
		return cCityID;
	}

	public void setCCityID(Integer cCityID) {
		this.cCityID = cCityID;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isConsignee() {
		return consignee;
	}

	public void setConsignee(Boolean consignee) {
		this.consignee = consignee;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isConsignor() {
		return consignor;
	}

	public void setConsignor(Boolean consignor) {
		this.consignor = consignor;
	}

	@Basic
	@Column(name="contract_no", length=20)
	public String getContractNo() {
		return contractNo;
	}

	public void setContractNo(String contractNo) {
		this.contractNo = contractNo;
	}

	@Basic
	@Column(nullable=false)
	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	@Basic
	@Column(name="created_by", columnDefinition="INT", nullable=false)
	public Integer getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Basic
	@Column(name="credit_balance", nullable=false)
	public BigDecimal getCreditBalance() {
		return creditBalance;
	}

	public void setCreditBalance(BigDecimal creditBalance) {
		this.creditBalance = creditBalance;
	}

	@Basic
	@Column(name="credit_quota", columnDefinition="INT")
	public Integer getCreditQuota() {
		return creditQuota;
	}

	public void setCreditQuota(Integer creditQuota) {
		this.creditQuota = creditQuota;
	}

	@Basic
	@Column(name="date_firstsale")
	public String getDateFirstsale() {
		return dateFirstsale;
	}

	public void setDateFirstsale(String dateFirstsale) {
		this.dateFirstsale = dateFirstsale;
	}

	@Basic
	@Column(name="dock_addr", nullable=false, length=80)
	public String getDockAddr() {
		return dockAddr;
	}

	public void setDockAddr(String dockAddr) {
		this.dockAddr = dockAddr;
	}

	@Basic
	@Column(length=20)
	public String getFax() {
		return fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Basic
	@Column(name="important_note", length=60)
	public String getImportantNote() {
		return importantNote;
	}

	public void setImportantNote(String importantNote) {
		this.importantNote = importantNote;
	}

	@Basic
	@Column(name="industry_type", columnDefinition="INT")
	public Integer getIndustryType() {
		return industryType;
	}

	public void setIndustryType(Integer industryType) {
		this.industryType = industryType;
	}

	@Basic
	@Column(nullable=false, length=20)
	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Basic
	@Column(nullable=false, length=60)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Basic
	@Column(name="org_name", length=20)
	public String getOrgName() {
		return orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	@Basic
	@Column(name="pay_method", columnDefinition="INT")
	public Integer getPayMethod() {
		return payMethod;
	}

	public void setPayMethod(Integer payMethod) {
		this.payMethod = payMethod;
	}

	@Basic
	@Column(length=20)
	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Basic
	@Column(name="salesrep_user_id", columnDefinition="INT")
	public Integer getSalesrepUserID() {
		return salesrepUserID;
	}

	public void setSalesrepUserID(Integer salesrepUserID) {
		this.salesrepUserID = salesrepUserID;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isShipper() {
		return shipper;
	}

	public void setShipper(Boolean shipper) {
		this.shipper = shipper;
	}

	@Basic
	public String getUpdated() {
		return updated;
	}

	public void setUpdated(String updated) {
		this.updated = updated;
	}

	@Basic
	@Column(name="updated_by", columnDefinition="INT")
	public Integer getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Basic
	@Column(length=10)
	public String getZip() {
		return zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}
}