package com.freight.model;

import java.math.*;
import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.acuity.AcuityCustomizer
 */
@Entity
@Table(name="c_bpartner")
public class CBpartner extends com.freight.common.EntityBase {
	private static final long serialVersionUID = 1L;
	private BigDecimal accoutBalance;
	private Boolean active;
	private String addr;
	private Integer cBpartnerId;
	private Integer cCityId;
	private Integer cClientId;
	private Integer cOrgId;
	private Boolean consignee;
	private Boolean consignor;
	private String contractNo;
	private Date created;
	private Integer createdby;
	private BigDecimal creditBalance;
	private Integer creditQuota;
	private Date dateFirstsale;
	private String dockAddr;
	private String fax;
	private String importantNote;
	private String industryType;
	private String mobile;
	private String name;
	private String orgName;
	private Integer payMethod;
	private String phone;
	private Integer salesrepUserId;
	private Boolean shipper;
	private Date updated;
	private Integer updatedby;
	private String zip;

	public CBpartner() {
	}

	public CBpartner(Integer cBpartnerId) {
		this.cBpartnerId = cBpartnerId;
	}

	@Basic
	@Column(name="accout_balance", nullable=false)
	public BigDecimal getAccoutBalance() {
		return accoutBalance;
	}

	public void setAccoutBalance(BigDecimal accoutBalance) {
		this.accoutBalance = accoutBalance;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Basic
	@Column(nullable=false, length=80)
	public String getAddr() {
		return addr;
	}

	public void setAddr(String addr) {
		this.addr = addr;
	}

	@Id
	@Column(name="c_bpartner_id", columnDefinition="INT")
	@TableGenerator(name = "PkGen_103", table = "c_sequence", pkColumnName = "name", pkColumnValue = "C_Bpartner", valueColumnName = "currentnextsys", allocationSize = 1 )
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "PkGen_103")
	public Integer getCBpartnerId() {
		return cBpartnerId;
	}

	public void setCBpartnerId(Integer cBpartnerId) {
		this.cBpartnerId = cBpartnerId;
	}

	@Basic
	@Column(name="c_city_id", columnDefinition="INT", nullable=false)
	public Integer getCCityId() {
		return cCityId;
	}

	public void setCCityId(Integer cCityId) {
		this.cCityId = cCityId;
	}

	@Basic
	@Column(name="c_client_id", columnDefinition="INT", nullable=false)
	public Integer getCClientId() {
		return cClientId;
	}

	public void setCClientId(Integer cClientId) {
		this.cClientId = cClientId;
	}

	@Basic
	@Column(name="c_org_id", columnDefinition="INT", nullable=false)
	public Integer getCOrgId() {
		return cOrgId;
	}

	public void setCOrgId(Integer cOrgId) {
		this.cOrgId = cOrgId;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isConsignee() {
		return consignee;
	}

	public void setConsignee(Boolean consignee) {
		this.consignee = consignee;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isConsignor() {
		return consignor;
	}

	public void setConsignor(Boolean consignor) {
		this.consignor = consignor;
	}

	@Basic
	@Column(name="contract_no", length=20)
	public String getContractNo() {
		return contractNo;
	}

	public void setContractNo(String contractNo) {
		this.contractNo = contractNo;
	}

	@Basic
	@Column(nullable=false)
	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getCreatedby() {
		return createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	@Basic
	@Column(name="credit_balance", nullable=false)
	public BigDecimal getCreditBalance() {
		return creditBalance;
	}

	public void setCreditBalance(BigDecimal creditBalance) {
		this.creditBalance = creditBalance;
	}

	@Basic
	@Column(name="credit_quota", columnDefinition="INT")
	public Integer getCreditQuota() {
		return creditQuota;
	}

	public void setCreditQuota(Integer creditQuota) {
		this.creditQuota = creditQuota;
	}

	@Basic
	@Column(name="date_firstsale")
	@Temporal(TemporalType.DATE)
	public Date getDateFirstsale() {
		return dateFirstsale;
	}

	public void setDateFirstsale(Date dateFirstsale) {
		this.dateFirstsale = dateFirstsale;
	}

	@Basic
	@Column(name="dock_addr", nullable=false, length=80)
	public String getDockAddr() {
		return dockAddr;
	}

	public void setDockAddr(String dockAddr) {
		this.dockAddr = dockAddr;
	}

	@Basic
	@Column(length=20)
	public String getFax() {
		return fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Basic
	@Column(name="important_note", length=60)
	public String getImportantNote() {
		return importantNote;
	}

	public void setImportantNote(String importantNote) {
		this.importantNote = importantNote;
	}

	@Basic
	@Column(name="industry_type", length=20)
	public String getIndustryType() {
		return industryType;
	}

	public void setIndustryType(String industryType) {
		this.industryType = industryType;
	}

	@Basic
	@Column(nullable=false, length=20)
	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Basic
	@Column(nullable=false, length=60)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Basic
	@Column(name="org_name", length=20)
	public String getOrgName() {
		return orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	@Basic
	@Column(name="pay_method", columnDefinition="INT")
	public Integer getPayMethod() {
		return payMethod;
	}

	public void setPayMethod(Integer payMethod) {
		this.payMethod = payMethod;
	}

	@Basic
	@Column(length=20)
	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Basic
	@Column(name="salesrep_user_id", columnDefinition="INT")
	public Integer getSalesrepUserId() {
		return salesrepUserId;
	}

	public void setSalesrepUserId(Integer salesrepUserId) {
		this.salesrepUserId = salesrepUserId;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isShipper() {
		return shipper;
	}

	public void setShipper(Boolean shipper) {
		this.shipper = shipper;
	}

	@Basic
	public Date getUpdated() {
		return updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Basic
	@Column(columnDefinition="INT")
	public Integer getUpdatedby() {
		return updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}

	@Basic
	@Column(length=10)
	public String getZip() {
		return zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}
}