package com.freight.model;

import javax.persistence.*;

import com.freight.common.EntityBase;

/**
 * Auto-generated by: org.freight.AdempiereCustomizer
 */
@Entity
@Table(name = "c_bpartner_contact")
public class CBPartnerContact extends EntityBase {

    private static final long serialVersionUID = 1L;
    private Integer           aDClientID;
    private Integer           aDOrgID;
    private Boolean           active;
    private String            addr;
    private String            birthday;
    private Integer           cBpartnerContactID;
    private Integer           cBpartnerID;
    private String            character;
    private String            created;
    private Integer           createdBy;
    private String            department;
    private String            email;
    private String            fax;
    private String            hobbies;
    private String            importantNote;
    private String            mobile;
    private String            name;
    private String            phone;
    private String            post;
    private Boolean           sex;
    private String            updated;
    private Integer           updatedBy;
    private String            zip;

    public CBPartnerContact(){
    }

    public CBPartnerContact(Integer cBpartnerContactID){
        this.cBpartnerContactID = cBpartnerContactID;
    }

    @Basic
    @Column(name = "ad_client_id", columnDefinition = "INT", nullable = false)
    public Integer getADClientID() {
        return aDClientID;
    }

    public void setADClientID(Integer aDClientID) {
        this.aDClientID = aDClientID;
    }

    @Basic
    @Column(name = "ad_org_id", columnDefinition = "INT", nullable = false)
    public Integer getADOrgID() {
        return aDOrgID;
    }

    public void setADOrgID(Integer aDOrgID) {
        this.aDOrgID = aDOrgID;
    }

    @Basic
    @Column(nullable = false)
    public Boolean isActive() {
        return active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    @Basic
    @Column(nullable = false, length = 200)
    public String getAddr() {
        return addr;
    }

    public void setAddr(String addr) {
        this.addr = addr;
    }

    @Basic
    public String getBirthday() {
        return birthday;
    }

    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    @Id
    @Column(name = "c_bpartner_contact_id", columnDefinition = "INT")
    @TableGenerator(name = "PkGen_112", table = "ad_sequence", pkColumnName = "name", pkColumnValue = "C_BPartner_Contact", valueColumnName = "currentnextsys", allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.TABLE, generator = "PkGen_112")
    public Integer getCBpartnerContactID() {
        return cBpartnerContactID;
    }

    public void setCBpartnerContactID(Integer cBpartnerContactID) {
        this.cBpartnerContactID = cBpartnerContactID;
    }

    @Basic
    @Column(name = "c_bpartner_id", columnDefinition = "INT", nullable = false)
    public Integer getCBpartnerID() {
        return cBpartnerID;
    }

    public void setCBpartnerID(Integer cBpartnerID) {
        this.cBpartnerID = cBpartnerID;
    }

    @Basic
    @Column(length = 50)
    public String getCharacter() {
        return character;
    }

    public void setCharacter(String character) {
        this.character = character;
    }

    @Basic
    @Column(nullable = false)
    public String getCreated() {
        return created;
    }

    public void setCreated(String created) {
        this.created = created;
    }

    @Basic
    @Column(name = "created_by", columnDefinition = "INT", nullable = false)
    public Integer getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    @Basic
    @Column(length = 20)
    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

    @Basic
    @Column(length = 30)
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Basic
    @Column(length = 20)
    public String getFax() {
        return fax;
    }

    public void setFax(String fax) {
        this.fax = fax;
    }

    @Basic
    @Column(length = 50)
    public String getHobbies() {
        return hobbies;
    }

    public void setHobbies(String hobbies) {
        this.hobbies = hobbies;
    }

    @Basic
    @Column(name = "important_note", length = 50)
    public String getImportantNote() {
        return importantNote;
    }

    public void setImportantNote(String importantNote) {
        this.importantNote = importantNote;
    }

    @Basic
    @Column(length = 20)
    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    @Basic
    @Column(length = 50)
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Basic
    @Column(length = 20)
    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Basic
    @Column(length = 20)
    public String getPost() {
        return post;
    }

    public void setPost(String post) {
        this.post = post;
    }

    @Basic
    @Column(nullable = false)
    public Boolean isSex() {
        return sex;
    }

    public void setSex(Boolean sex) {
        this.sex = sex;
    }

    @Basic
    public String getUpdated() {
        return updated;
    }

    public void setUpdated(String updated) {
        this.updated = updated;
    }

    @Basic
    @Column(name = "updated_by", columnDefinition = "INT")
    public Integer getUpdatedBy() {
        return updatedBy;
    }

    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Basic
    @Column(length = 10)
    public String getZip() {
        return zip;
    }

    public void setZip(String zip) {
        this.zip = zip;
    }
}
