package com.freight.model;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.acuity.AcuityCustomizer
 */
@Entity
@Table(name="c_complaint")
public class CComplaint extends com.freight.common.EntityBase {
	private static final long serialVersionUID = 1L;
	private Boolean active;
	private Integer cClientId;
	private Integer cComplaintId;
	private Integer cOrderId;
	private String comment;
	private Date created;
	private Integer createdby;
	private Date dateHandle;
	private Date dateOperation;
	private String handleMethod;
	private String handleOrgId;
	private String handleUserId;
	private String relatedUserId;
	private String status;
	private Date updated;
	private Integer updatedby;

	public CComplaint() {
	}

	public CComplaint(Integer cComplaintId) {
		this.cComplaintId = cComplaintId;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Basic
	@Column(name="c_client_id", columnDefinition="INT", nullable=false)
	public Integer getCClientId() {
		return cClientId;
	}

	public void setCClientId(Integer cClientId) {
		this.cClientId = cClientId;
	}

	@Id
	@Column(name="c_complaint_id", columnDefinition="INT")
	@TableGenerator(name = "PkGen_105", table = "c_sequence", pkColumnName = "name", pkColumnValue = "C_Complaint", valueColumnName = "currentnextsys", allocationSize = 1 )
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "PkGen_105")
	public Integer getCComplaintId() {
		return cComplaintId;
	}

	public void setCComplaintId(Integer cComplaintId) {
		this.cComplaintId = cComplaintId;
	}

	@Basic
	@Column(name="c_order_id", columnDefinition="INT")
	public Integer getCOrderId() {
		return cOrderId;
	}

	public void setCOrderId(Integer cOrderId) {
		this.cOrderId = cOrderId;
	}

	@Basic
	@Column(length=20)
	public String getComment() {
		return comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Basic
	@Column(nullable=false)
	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getCreatedby() {
		return createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	@Basic
	@Column(name="date_handle")
	public Date getDateHandle() {
		return dateHandle;
	}

	public void setDateHandle(Date dateHandle) {
		this.dateHandle = dateHandle;
	}

	@Basic
	@Column(name="date_operation")
	public Date getDateOperation() {
		return dateOperation;
	}

	public void setDateOperation(Date dateOperation) {
		this.dateOperation = dateOperation;
	}

	@Basic
	@Column(name="handle_method", length=200)
	public String getHandleMethod() {
		return handleMethod;
	}

	public void setHandleMethod(String handleMethod) {
		this.handleMethod = handleMethod;
	}

	@Basic
	@Column(name="handle_org_id", length=10)
	public String getHandleOrgId() {
		return handleOrgId;
	}

	public void setHandleOrgId(String handleOrgId) {
		this.handleOrgId = handleOrgId;
	}

	@Basic
	@Column(name="handle_user_id", length=20)
	public String getHandleUserId() {
		return handleUserId;
	}

	public void setHandleUserId(String handleUserId) {
		this.handleUserId = handleUserId;
	}

	@Basic
	@Column(name="related_user_id", length=20)
	public String getRelatedUserId() {
		return relatedUserId;
	}

	public void setRelatedUserId(String relatedUserId) {
		this.relatedUserId = relatedUserId;
	}

	@Basic
	@Column(nullable=false, length=10)
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Basic
	public Date getUpdated() {
		return updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Basic
	@Column(columnDefinition="INT")
	public Integer getUpdatedby() {
		return updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}
}