package com.freight.model;

import javax.persistence.*;

import com.freight.common.EntityBase;

/**
 * Auto-generated by:
 * org.freight.AdempiereCustomizer
 */
@Entity
@Table(name="c_complaint")
public class CComplaint extends EntityBase {
	private static final long serialVersionUID = 1L;
	private Integer aDClientID;
	private Boolean active;
	private Integer cComplaintID;
	private Integer cOrderID;
	private String comment;
	private String created;
	private Integer createdBy;
	private String dateHandle;
	private String dateOperation;
	private String handleMethod;
	private String handleOrgID;
	private String handleUserID;
	private String relatedUserID;
	private String status;
	private String updated;
	private Integer updatedBy;

	public CComplaint() {
	}

	public CComplaint(Integer cComplaintID) {
		this.cComplaintID = cComplaintID;
	}

	@Basic
	@Column(name="ad_client_id", columnDefinition="INT", nullable=false)
	public Integer getADClientID() {
		return aDClientID;
	}

	public void setADClientID(Integer aDClientID) {
		this.aDClientID = aDClientID;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Id
	@Column(name="c_complaint_id", columnDefinition="INT")
	@TableGenerator(name = "PkGen_113", table = "ad_sequence", pkColumnName = "name", pkColumnValue = "C_Complaint", valueColumnName = "currentnextsys", allocationSize = 1 )
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "PkGen_113")
	public Integer getCComplaintID() {
		return cComplaintID;
	}

	public void setCComplaintID(Integer cComplaintID) {
		this.cComplaintID = cComplaintID;
	}

	@Basic
	@Column(name="c_order_id", columnDefinition="INT")
	public Integer getCOrderID() {
		return cOrderID;
	}

	public void setCOrderID(Integer cOrderID) {
		this.cOrderID = cOrderID;
	}

	@Basic
	@Column(length=20)
	public String getComment() {
		return comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Basic
	@Column(nullable=false)
	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	@Basic
	@Column(name="created_by", columnDefinition="INT", nullable=false)
	public Integer getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Basic
	@Column(name="date_handle")
	public String getDateHandle() {
		return dateHandle;
	}

	public void setDateHandle(String dateHandle) {
		this.dateHandle = dateHandle;
	}

	@Basic
	@Column(name="date_operation")
	public String getDateOperation() {
		return dateOperation;
	}

	public void setDateOperation(String dateOperation) {
		this.dateOperation = dateOperation;
	}

	@Basic
	@Column(name="handle_method", length=200)
	public String getHandleMethod() {
		return handleMethod;
	}

	public void setHandleMethod(String handleMethod) {
		this.handleMethod = handleMethod;
	}

	@Basic
	@Column(name="handle_org_id", length=10)
	public String getHandleOrgID() {
		return handleOrgID;
	}

	public void setHandleOrgID(String handleOrgID) {
		this.handleOrgID = handleOrgID;
	}

	@Basic
	@Column(name="handle_user_id", length=20)
	public String getHandleUserID() {
		return handleUserID;
	}

	public void setHandleUserID(String handleUserID) {
		this.handleUserID = handleUserID;
	}

	@Basic
	@Column(name="related_user_id", length=20)
	public String getRelatedUserID() {
		return relatedUserID;
	}

	public void setRelatedUserID(String relatedUserID) {
		this.relatedUserID = relatedUserID;
	}

	@Basic
	@Column(nullable=false, length=10)
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Basic
	public String getUpdated() {
		return updated;
	}

	public void setUpdated(String updated) {
		this.updated = updated;
	}

	@Basic
	@Column(name="updated_by", columnDefinition="INT")
	public Integer getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}
}