package com.freight.model;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

import com.freight.common.EntityBase;

/**
 * Auto-generated by:
 * org.freight.AdempiereCustomizer
 */
@Entity
@Table(name="c_inout_line")
public class CInoutLine extends EntityBase {
	private static final long serialVersionUID = 1L;
	private Integer aDClientID;
	private Integer aDOrgID;
	private Boolean active;
	private Integer cInoutID;
	private Integer cInoutLineID;
	private Integer cOrderID;
	private Integer cOrderLineID;
	private String created;
	private Integer createdBy;
	private Integer moveQty;
	private Integer pickQty;
	private Integer scrappedQty;
	private Integer targetQty;
	private Integer confirmedQty;
	private String updated;
	private Integer updatedBy;

	public CInoutLine() {
	}

	public CInoutLine(Integer cInoutLineID) {
		this.cInoutLineID = cInoutLineID;
	}

	@Basic
	@Column(name="ad_client_id", columnDefinition="INT", nullable=false)
	public Integer getADClientID() {
		return aDClientID;
	}

	public void setADClientID(Integer aDClientID) {
		this.aDClientID = aDClientID;
	}

	@Basic
	@Column(name="ad_org_id", columnDefinition="INT", nullable=false)
	public Integer getADOrgID() {
		return aDOrgID;
	}

	public void setADOrgID(Integer aDOrgID) {
		this.aDOrgID = aDOrgID;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Basic
	@Column(name="c_inout_id", columnDefinition="INT", nullable=false)
	public Integer getCInoutID() {
		return cInoutID;
	}

	public void setCInoutID(Integer cInoutID) {
		this.cInoutID = cInoutID;
	}

	@Id
	@Column(name="c_inout_line_id", columnDefinition="INT")
	@TableGenerator(name = "PkGen_115", table = "ad_sequence", pkColumnName = "name", pkColumnValue = "C_Inout_Line", valueColumnName = "currentnextsys", allocationSize = 1 )
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "PkGen_115")
	public Integer getCInoutLineID() {
		return cInoutLineID;
	}

	public void setCInoutLineID(Integer cInoutLineID) {
		this.cInoutLineID = cInoutLineID;
	}
	
	@Basic
	@Column(name="c_order_id", columnDefinition="INT", nullable=false)
	public Integer getCOrderID() {
		return cOrderID;
	}

	public void setCOrderID(Integer cOrderID) {
		this.cOrderID = cOrderID;
	}

	@Basic
	@Column(name="c_order_line_id", columnDefinition="INT", nullable=false)
	public Integer getCOrderLineID() {
		return cOrderLineID;
	}

	public void setCOrderLineID(Integer cOrderLineID) {
		this.cOrderLineID = cOrderLineID;
	}

	@Basic
	@Column(name="confirmed_qty")
	public Integer getConfirmedQty() {
		return confirmedQty;
	}

	public void setConfirmedQty(Integer confirmedQty) {
		this.confirmedQty = confirmedQty;
	}

	@Basic
	@Column(nullable=false)
	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	@Basic
	@Column(name="created_by", columnDefinition="INT", nullable=false)
	public Integer getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Basic
	@Column(name="move_qty", nullable=false)
	public Integer getMoveQty() {
		return moveQty;
	}

	public void setMoveQty(Integer moveQty) {
		this.moveQty = moveQty;
	}

	@Basic
	@Column(name="pick_qty")
	public Integer getPickQty() {
		return pickQty;
	}

	public void setPickQty(Integer pickQty) {
		this.pickQty = pickQty;
	}

	@Basic
	@Column(name="scrapped_qty")
	public Integer getScrappedQty() {
		return scrappedQty;
	}

	public void setScrappedQty(Integer scrappedQty) {
		this.scrappedQty = scrappedQty;
	}

	@Basic
	@Column(name="target_qty")
	public Integer getTargetQty() {
		return targetQty;
	}

	public void setTargetQty(Integer targetQty) {
		this.targetQty = targetQty;
	}

	@Basic
	public String getUpdated() {
		return updated;
	}

	public void setUpdated(String updated) {
		this.updated = updated;
	}

	@Basic
	@Column(name="updated_by", columnDefinition="INT")
	public Integer getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}
}