package com.freight.model;

import java.math.*;
import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.acuity.AcuityCustomizer
 */
@Entity
@Table(name="c_inout")
public class CInout extends com.freight.common.EntityBase {
	private static final long serialVersionUID = 1L;
	private Boolean active;
	private Integer cClientId;
	private Integer cInoutId;
	private Integer cMoveId;
	private Integer cOrderId;
	private Integer cOrgId;
	private Integer cWarehouseId;
	private String comment;
	private Date created;
	private Integer createdby;
	private Integer handleMethod;
	private String inoutType;
	private Integer signedBpartnerId;
	private String signedType;
	private Integer signedUserId;
	private Date timeInouted;
	private Integer totalAmount;
	private BigDecimal totalVolume;
	private BigDecimal totalWeight;
	private Date updated;
	private Integer updatedby;

	public CInout() {
	}

	public CInout(Integer cInoutId) {
		this.cInoutId = cInoutId;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Basic
	@Column(name="c_client_id", columnDefinition="INT", nullable=false)
	public Integer getCClientId() {
		return cClientId;
	}

	public void setCClientId(Integer cClientId) {
		this.cClientId = cClientId;
	}

	@Id
	@Column(name="c_inout_id", columnDefinition="INT")
	@TableGenerator(name = "PkGen_106", table = "c_sequence", pkColumnName = "name", pkColumnValue = "C_Inout", valueColumnName = "currentnextsys", allocationSize = 1 )
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "PkGen_106")
	public Integer getCInoutId() {
		return cInoutId;
	}

	public void setCInoutId(Integer cInoutId) {
		this.cInoutId = cInoutId;
	}

	@Basic
	@Column(name="c_move_id", columnDefinition="INT")
	public Integer getCMoveId() {
		return cMoveId;
	}

	public void setCMoveId(Integer cMoveId) {
		this.cMoveId = cMoveId;
	}

	@Basic
	@Column(name="c_order_id", columnDefinition="INT")
	public Integer getCOrderId() {
		return cOrderId;
	}

	public void setCOrderId(Integer cOrderId) {
		this.cOrderId = cOrderId;
	}

	@Basic
	@Column(name="c_org_id", columnDefinition="INT", nullable=false)
	public Integer getCOrgId() {
		return cOrgId;
	}

	public void setCOrgId(Integer cOrgId) {
		this.cOrgId = cOrgId;
	}

	@Basic
	@Column(name="c_warehouse_id", columnDefinition="INT")
	public Integer getCWarehouseId() {
		return cWarehouseId;
	}

	public void setCWarehouseId(Integer cWarehouseId) {
		this.cWarehouseId = cWarehouseId;
	}

	@Basic
	@Column(length=60)
	public String getComment() {
		return comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Basic
	@Column(nullable=false)
	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getCreatedby() {
		return createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	@Basic
	@Column(name="handle_method", columnDefinition="INT")
	public Integer getHandleMethod() {
		return handleMethod;
	}

	public void setHandleMethod(Integer handleMethod) {
		this.handleMethod = handleMethod;
	}

	@Basic
	@Column(name="inout_type", nullable=false, length=3)
	public String getInoutType() {
		return inoutType;
	}

	public void setInoutType(String inoutType) {
		this.inoutType = inoutType;
	}

	@Basic
	@Column(name="signed_bpartner_id", columnDefinition="INT")
	public Integer getSignedBpartnerId() {
		return signedBpartnerId;
	}

	public void setSignedBpartnerId(Integer signedBpartnerId) {
		this.signedBpartnerId = signedBpartnerId;
	}

	@Basic
	@Column(name="signed_type", length=3)
	public String getSignedType() {
		return signedType;
	}

	public void setSignedType(String signedType) {
		this.signedType = signedType;
	}

	@Basic
	@Column(name="signed_user_id", columnDefinition="INT")
	public Integer getSignedUserId() {
		return signedUserId;
	}

	public void setSignedUserId(Integer signedUserId) {
		this.signedUserId = signedUserId;
	}

	@Basic
	@Column(name="time_inouted", nullable=false)
	public Date getTimeInouted() {
		return timeInouted;
	}

	public void setTimeInouted(Date timeInouted) {
		this.timeInouted = timeInouted;
	}

	@Basic
	@Column(name="total_amount", columnDefinition="INT")
	public Integer getTotalAmount() {
		return totalAmount;
	}

	public void setTotalAmount(Integer totalAmount) {
		this.totalAmount = totalAmount;
	}

	@Basic
	@Column(name="total_volume")
	public BigDecimal getTotalVolume() {
		return totalVolume;
	}

	public void setTotalVolume(BigDecimal totalVolume) {
		this.totalVolume = totalVolume;
	}

	@Basic
	@Column(name="total_weight")
	public BigDecimal getTotalWeight() {
		return totalWeight;
	}

	public void setTotalWeight(BigDecimal totalWeight) {
		this.totalWeight = totalWeight;
	}

	@Basic
	public Date getUpdated() {
		return updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Basic
	@Column(columnDefinition="INT")
	public Integer getUpdatedby() {
		return updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}
}