package com.freight.model;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.acuity.AcuityCustomizer
 */
@Entity
@Table(name="c_inventory")
public class CInventory extends com.freight.common.EntityBase {
	private static final long serialVersionUID = 1L;
	private Boolean active;
	private Integer cClientId;
	private Integer cInoutLineId;
	private Integer cInventoryId;
	private Integer cOrderId;
	private Integer cOrderLineId;
	private Integer cOrgId;
	private Integer cWarehouseId;
	private Date created;
	private Integer createdby;
	private Date updated;
	private Integer updatedby;

	public CInventory() {
	}

	public CInventory(Integer cInventoryId) {
		this.cInventoryId = cInventoryId;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Basic
	@Column(name="c_client_id", columnDefinition="INT", nullable=false)
	public Integer getCClientId() {
		return cClientId;
	}

	public void setCClientId(Integer cClientId) {
		this.cClientId = cClientId;
	}

	@Basic
	@Column(name="c_inout_line_id", columnDefinition="INT", nullable=false)
	public Integer getCInoutLineId() {
		return cInoutLineId;
	}

	public void setCInoutLineId(Integer cInoutLineId) {
		this.cInoutLineId = cInoutLineId;
	}

	@Id
	@Column(name="c_inventory_id", columnDefinition="INT")
	@TableGenerator(name = "PkGen_108", table = "c_sequence", pkColumnName = "name", pkColumnValue = "C_Inventory", valueColumnName = "currentnextsys", allocationSize = 1 )
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "PkGen_108")
	public Integer getCInventoryId() {
		return cInventoryId;
	}

	public void setCInventoryId(Integer cInventoryId) {
		this.cInventoryId = cInventoryId;
	}

	@Basic
	@Column(name="c_order_id", columnDefinition="INT")
	public Integer getCOrderId() {
		return cOrderId;
	}

	public void setCOrderId(Integer cOrderId) {
		this.cOrderId = cOrderId;
	}

	@Basic
	@Column(name="c_order_line_id", columnDefinition="INT")
	public Integer getCOrderLineId() {
		return cOrderLineId;
	}

	public void setCOrderLineId(Integer cOrderLineId) {
		this.cOrderLineId = cOrderLineId;
	}

	@Basic
	@Column(name="c_org_id", columnDefinition="INT", nullable=false)
	public Integer getCOrgId() {
		return cOrgId;
	}

	public void setCOrgId(Integer cOrgId) {
		this.cOrgId = cOrgId;
	}

	@Basic
	@Column(name="c_warehouse_id", columnDefinition="INT", nullable=false)
	public Integer getCWarehouseId() {
		return cWarehouseId;
	}

	public void setCWarehouseId(Integer cWarehouseId) {
		this.cWarehouseId = cWarehouseId;
	}

	@Basic
	@Column(nullable=false)
	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getCreatedby() {
		return createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	@Basic
	public Date getUpdated() {
		return updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Basic
	@Column(columnDefinition="INT")
	public Integer getUpdatedby() {
		return updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}
}