package com.freight.model;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.acuity.AcuityCustomizer
 */
@Entity
@Table(name="c_move_track")
public class CMoveTrack extends com.freight.common.EntityBase {
	private static final long serialVersionUID = 1L;
	private Boolean active;
	private Integer cClientId;
	private Integer cMoveId;
	private Integer cMoveTrackId;
	private Integer cOrgId;
	private String comment;
	private String contactDriver;
	private Date created;
	private Integer createdby;
	private String expectNote;
	private Date timePosition;
	private Date updated;
	private Integer updatedby;

	public CMoveTrack() {
	}

	public CMoveTrack(Integer cMoveTrackId) {
		this.cMoveTrackId = cMoveTrackId;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Basic
	@Column(name="c_client_id", columnDefinition="INT", nullable=false)
	public Integer getCClientId() {
		return cClientId;
	}

	public void setCClientId(Integer cClientId) {
		this.cClientId = cClientId;
	}

	@Basic
	@Column(name="c_move_id", columnDefinition="INT", nullable=false)
	public Integer getCMoveId() {
		return cMoveId;
	}

	public void setCMoveId(Integer cMoveId) {
		this.cMoveId = cMoveId;
	}

	@Id
	@Column(name="c_move_track_id", columnDefinition="INT")
	@TableGenerator(name = "PkGen_111", table = "c_sequence", pkColumnName = "name", pkColumnValue = "C_Move_Track", valueColumnName = "currentnextsys", allocationSize = 1 )
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "PkGen_111")
	public Integer getCMoveTrackId() {
		return cMoveTrackId;
	}

	public void setCMoveTrackId(Integer cMoveTrackId) {
		this.cMoveTrackId = cMoveTrackId;
	}

	@Basic
	@Column(name="c_org_id", columnDefinition="INT", nullable=false)
	public Integer getCOrgId() {
		return cOrgId;
	}

	public void setCOrgId(Integer cOrgId) {
		this.cOrgId = cOrgId;
	}

	@Basic
	@Column(length=50)
	public String getComment() {
		return comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Basic
	@Column(name="contact_driver", nullable=false, length=20)
	public String getContactDriver() {
		return contactDriver;
	}

	public void setContactDriver(String contactDriver) {
		this.contactDriver = contactDriver;
	}

	@Basic
	@Column(nullable=false)
	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getCreatedby() {
		return createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	@Basic
	@Column(name="expect_note", length=50)
	public String getExpectNote() {
		return expectNote;
	}

	public void setExpectNote(String expectNote) {
		this.expectNote = expectNote;
	}

	@Basic
	@Column(name="time_position", nullable=false)
	public Date getTimePosition() {
		return timePosition;
	}

	public void setTimePosition(Date timePosition) {
		this.timePosition = timePosition;
	}

	@Basic
	public Date getUpdated() {
		return updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Basic
	@Column(columnDefinition="INT")
	public Integer getUpdatedby() {
		return updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}
}