package com.freight.model;

import java.math.*;
import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.acuity.AcuityCustomizer
 */
@Entity
@Table(name="c_move")
public class CMove extends com.freight.common.EntityBase {
	private static final long serialVersionUID = 1L;
	private Boolean active;
	private Integer cClientId;
	private String cMoveId;
	private Integer cOrderId;
	private Integer cOrgId;
	private String contractNo;
	private Date created;
	private Integer createdby;
	private Date dateOrdered;
	private Date datePromise;
	private String deliveryRule;
	private Integer departOrgId;
	private Integer destinationOrgId;
	private Date timeArrived;
	private Date timeDeparted;
	private BigDecimal totalAmount;
	private BigDecimal totalCharge;
	private BigDecimal totalVolume;
	private BigDecimal totalWeight;
	private Date updated;
	private Integer updatedby;

	public CMove() {
	}

	public CMove(String cMoveId) {
		this.cMoveId = cMoveId;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Basic
	@Column(name="c_client_id", columnDefinition="INT", nullable=false)
	public Integer getCClientId() {
		return cClientId;
	}

	public void setCClientId(Integer cClientId) {
		this.cClientId = cClientId;
	}

	@Id
	@Column(name="c_move_id", length=20)
	@TableGenerator(name = "PkGen_109", table = "c_sequence", pkColumnName = "name", pkColumnValue = "C_Move", valueColumnName = "currentnextsys", allocationSize = 1 )
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "PkGen_109")
	public String getCMoveId() {
		return cMoveId;
	}

	public void setCMoveId(String cMoveId) {
		this.cMoveId = cMoveId;
	}

	@Basic
	@Column(name="c_order_id", columnDefinition="INT")
	public Integer getCOrderId() {
		return cOrderId;
	}

	public void setCOrderId(Integer cOrderId) {
		this.cOrderId = cOrderId;
	}

	@Basic
	@Column(name="c_org_id", columnDefinition="INT", nullable=false)
	public Integer getCOrgId() {
		return cOrgId;
	}

	public void setCOrgId(Integer cOrgId) {
		this.cOrgId = cOrgId;
	}

	@Basic
	@Column(name="contract_no", nullable=false, length=20)
	public String getContractNo() {
		return contractNo;
	}

	public void setContractNo(String contractNo) {
		this.contractNo = contractNo;
	}

	@Basic
	@Column(nullable=false)
	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getCreatedby() {
		return createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	@Basic
	@Column(name="date_ordered", nullable=false)
	public Date getDateOrdered() {
		return dateOrdered;
	}

	public void setDateOrdered(Date dateOrdered) {
		this.dateOrdered = dateOrdered;
	}

	@Basic
	@Column(name="date_promise", nullable=false)
	public Date getDatePromise() {
		return datePromise;
	}

	public void setDatePromise(Date datePromise) {
		this.datePromise = datePromise;
	}

	@Basic
	@Column(name="delivery_rule", nullable=false, length=2)
	public String getDeliveryRule() {
		return deliveryRule;
	}

	public void setDeliveryRule(String deliveryRule) {
		this.deliveryRule = deliveryRule;
	}

	@Basic
	@Column(name="depart_org_id", columnDefinition="INT")
	public Integer getDepartOrgId() {
		return departOrgId;
	}

	public void setDepartOrgId(Integer departOrgId) {
		this.departOrgId = departOrgId;
	}

	@Basic
	@Column(name="destination_org_id", columnDefinition="INT")
	public Integer getDestinationOrgId() {
		return destinationOrgId;
	}

	public void setDestinationOrgId(Integer destinationOrgId) {
		this.destinationOrgId = destinationOrgId;
	}

	@Basic
	@Column(name="time_arrived")
	public Date getTimeArrived() {
		return timeArrived;
	}

	public void setTimeArrived(Date timeArrived) {
		this.timeArrived = timeArrived;
	}

	@Basic
	@Column(name="time_departed")
	public Date getTimeDeparted() {
		return timeDeparted;
	}

	public void setTimeDeparted(Date timeDeparted) {
		this.timeDeparted = timeDeparted;
	}

	@Basic
	@Column(name="total_amount", nullable=false)
	public BigDecimal getTotalAmount() {
		return totalAmount;
	}

	public void setTotalAmount(BigDecimal totalAmount) {
		this.totalAmount = totalAmount;
	}

	@Basic
	@Column(name="total_charge", nullable=false)
	public BigDecimal getTotalCharge() {
		return totalCharge;
	}

	public void setTotalCharge(BigDecimal totalCharge) {
		this.totalCharge = totalCharge;
	}

	@Basic
	@Column(name="total_volume", nullable=false)
	public BigDecimal getTotalVolume() {
		return totalVolume;
	}

	public void setTotalVolume(BigDecimal totalVolume) {
		this.totalVolume = totalVolume;
	}

	@Basic
	@Column(name="total_weight", nullable=false)
	public BigDecimal getTotalWeight() {
		return totalWeight;
	}

	public void setTotalWeight(BigDecimal totalWeight) {
		this.totalWeight = totalWeight;
	}

	@Basic
	public Date getUpdated() {
		return updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Basic
	@Column(columnDefinition="INT")
	public Integer getUpdatedby() {
		return updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}
}