package com.freight.model;

import java.math.*;
import javax.persistence.*;

import com.freight.common.EntityBase;

/**
 * Auto-generated by: org.freight.AdempiereCustomizer
 */
@Entity
@Table(name = "c_move_v")
public class CMoveV extends EntityBase {
	private static final long serialVersionUID = 1L;
	private String arriveOrgName;
	private Integer cMoveID;
	private Integer cOrderID;
	private Integer cVehicleID;
	private BigDecimal chargeFreight;
	private String contractNo;
	private String datePromise;
	private Integer departOrgID;
	private String departOrgName;
	private Integer destOrgID;
	private String driverName;
	private String driverPhone;
	private Integer driverUserID;
	private Integer moveStatus;
	private Integer moveType;
	private String ownerName;
	private String ownerPhone;
	private BigDecimal paidArrive;
	private BigDecimal paidDepart;
	private BigDecimal paidReceipt;
	private String timeArrived;
	private String timeDeparted;
	private Integer totalAmount;
	private BigDecimal totalFreight;
	private BigDecimal totalVolume;
	private BigDecimal totalWeight;
	private Integer vehicleNature;
	private String plateNo;

	public CMoveV() {
	}

	public CMoveV(Integer cMoveID) {
		this.cMoveID = cMoveID;
	}

	@Basic
	@Column(name = "arrive_org_name", length = 60)
	public String getArriveOrgName() {
		return arriveOrgName;
	}

	public void setArriveOrgName(String arriveOrgName) {
		this.arriveOrgName = arriveOrgName;
	}

	@Id
	@Column(name = "c_move_id", columnDefinition = "INT")
	public Integer getCMoveID() {
		return cMoveID;
	}

	public void setCMoveID(Integer cMoveID) {
		this.cMoveID = cMoveID;
	}

	@Basic
	@Column(name = "c_order_id", columnDefinition = "INT")
	public Integer getCOrderID() {
		return cOrderID;
	}

	public void setCOrderID(Integer cOrderID) {
		this.cOrderID = cOrderID;
	}

	@Basic
	@Column(name = "c_vehicle_id", columnDefinition = "INT", nullable = false)
	public Integer getCVehicleID() {
		return cVehicleID;
	}

	public void setCVehicleID(Integer cVehicleID) {
		this.cVehicleID = cVehicleID;
	}

	@Basic
	@Column(name = "charge_freight", nullable = false)
	public BigDecimal getChargeFreight() {
		return chargeFreight;
	}

	public void setChargeFreight(BigDecimal chargeFreight) {
		this.chargeFreight = chargeFreight;
	}

	@Basic
	@Column(name = "contract_no", nullable = false, length = 20)
	public String getContractNo() {
		return contractNo;
	}

	public void setContractNo(String contractNo) {
		this.contractNo = contractNo;
	}

	@Basic
	@Column(name = "date_promise")
	public String getDatePromise() {
		return datePromise;
	}

	public void setDatePromise(String datePromise) {
		this.datePromise = datePromise;
	}

	@Basic
	@Column(name = "depart_org_id", columnDefinition = "INT")
	public Integer getDepartOrgID() {
		return departOrgID;
	}

	public void setDepartOrgID(Integer departOrgID) {
		this.departOrgID = departOrgID;
	}

	@Basic
	@Column(name = "depart_org_name", length = 60)
	public String getDepartOrgName() {
		return departOrgName;
	}

	public void setDepartOrgName(String departOrgName) {
		this.departOrgName = departOrgName;
	}

	@Basic
	@Column(name = "dest_org_id", columnDefinition = "INT")
	public Integer getDestOrgID() {
		return destOrgID;
	}

	public void setDestOrgID(Integer destOrgID) {
		this.destOrgID = destOrgID;
	}

	@Basic
	@Column(name = "driver_name", length = 20)
	public String getDriverName() {
		return driverName;
	}

	public void setDriverName(String driverName) {
		this.driverName = driverName;
	}

	@Basic
	@Column(name = "driver_phone", length = 20)
	public String getDriverPhone() {
		return driverPhone;
	}

	public void setDriverPhone(String driverPhone) {
		this.driverPhone = driverPhone;
	}

	@Basic
	@Column(name = "driver_user_id", columnDefinition = "INT")
	public Integer getDriverUserID() {
		return driverUserID;
	}

	public void setDriverUserID(Integer driverUserID) {
		this.driverUserID = driverUserID;
	}

	@Basic
	@Column(name = "move_status", columnDefinition = "INT", nullable = false)
	public Integer getMoveStatus() {
		return moveStatus;
	}

	public void setMoveStatus(Integer moveStatus) {
		this.moveStatus = moveStatus;
	}

	@Basic
	@Column(name = "move_type", nullable = false)
	public Integer getMoveType() {
		return moveType;
	}

	public void setMoveType(Integer moveType) {
		this.moveType = moveType;
	}

	@Basic
	@Column(name = "owner_name", length = 20)
	public String getOwnerName() {
		return ownerName;
	}

	public void setOwnerName(String ownerName) {
		this.ownerName = ownerName;
	}

	@Basic
	@Column(name = "owner_phone", length = 20)
	public String getOwnerPhone() {
		return ownerPhone;
	}

	public void setOwnerPhone(String ownerPhone) {
		this.ownerPhone = ownerPhone;
	}

	@Basic
	@Column(name = "paid_arrive")
	public BigDecimal getPaidArrive() {
		return paidArrive;
	}

	public void setPaidArrive(BigDecimal paidArrive) {
		this.paidArrive = paidArrive;
	}

	@Basic
	@Column(name = "paid_depart")
	public BigDecimal getPaidDepart() {
		return paidDepart;
	}

	public void setPaidDepart(BigDecimal paidDepart) {
		this.paidDepart = paidDepart;
	}

	@Basic
	@Column(name = "paid_receipt")
	public BigDecimal getPaidReceipt() {
		return paidReceipt;
	}

	public void setPaidReceipt(BigDecimal paidReceipt) {
		this.paidReceipt = paidReceipt;
	}

	@Basic
	@Column(name = "time_arrived")
	public String getTimeArrived() {
		return timeArrived;
	}

	public void setTimeArrived(String timeArrived) {
		this.timeArrived = timeArrived;
	}

	@Basic
	@Column(name = "time_departed")
	public String getTimeDeparted() {
		return timeDeparted;
	}

	public void setTimeDeparted(String timeDeparted) {
		this.timeDeparted = timeDeparted;
	}

	@Basic
	@Column(name = "total_amount", nullable = false)
	public Integer getTotalAmount() {
		return totalAmount;
	}

	public void setTotalAmount(Integer totalAmount) {
		this.totalAmount = totalAmount;
	}

	@Basic
	@Column(name = "total_freight", nullable = false)
	public BigDecimal getTotalFreight() {
		return totalFreight;
	}

	public void setTotalFreight(BigDecimal totalFreight) {
		this.totalFreight = totalFreight;
	}

	@Basic
	@Column(name = "total_volume", nullable = false)
	public BigDecimal getTotalVolume() {
		return totalVolume;
	}

	public void setTotalVolume(BigDecimal totalVolume) {
		this.totalVolume = totalVolume;
	}

	@Basic
	@Column(name = "total_weight", nullable = false)
	public BigDecimal getTotalWeight() {
		return totalWeight;
	}

	public void setTotalWeight(BigDecimal totalWeight) {
		this.totalWeight = totalWeight;
	}

	@Basic
	@Column(name = "vehicle_nature")
	public Integer getVehicleNature() {
		return vehicleNature;
	}

	public void setVehicleNature(Integer vehicleNature) {
		this.vehicleNature = vehicleNature;
	}

	@Basic
	@Column(name = "plate_no")
	public String getPlateNo() {
		return plateNo;
	}

	public void setPlateNo(String plateNo) {
		this.plateNo = plateNo;
	}
	
	

}