package com.freight.model;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.acuity.AcuityCustomizer
 */
@Entity
@Table(name="c_move_line")
public class CMoveLine extends com.freight.common.EntityBase {
	private static final long serialVersionUID = 1L;
	private Boolean active;
	private Integer cClientId;
	private Integer cMoveId;
	private Integer cMoveLineId;
	private Integer cOrderLineId;
	private Integer cOrgId;
	private Date created;
	private Integer createdby;
	private Date updated;
	private Integer updatedby;

	public CMoveLine() {
	}

	public CMoveLine(Integer cMoveLineId) {
		this.cMoveLineId = cMoveLineId;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Basic
	@Column(name="c_client_id", columnDefinition="INT", nullable=false)
	public Integer getCClientId() {
		return cClientId;
	}

	public void setCClientId(Integer cClientId) {
		this.cClientId = cClientId;
	}

	@Basic
	@Column(name="c_move_id", columnDefinition="INT", nullable=false)
	public Integer getCMoveId() {
		return cMoveId;
	}

	public void setCMoveId(Integer cMoveId) {
		this.cMoveId = cMoveId;
	}

	@Id
	@Column(name="c_move_line_id", columnDefinition="INT")
	@TableGenerator(name = "PkGen_110", table = "c_sequence", pkColumnName = "name", pkColumnValue = "C_Move_Line", valueColumnName = "currentnextsys", allocationSize = 1 )
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "PkGen_110")
	public Integer getCMoveLineId() {
		return cMoveLineId;
	}

	public void setCMoveLineId(Integer cMoveLineId) {
		this.cMoveLineId = cMoveLineId;
	}

	@Basic
	@Column(name="c_order_line_id", columnDefinition="INT", nullable=false)
	public Integer getCOrderLineId() {
		return cOrderLineId;
	}

	public void setCOrderLineId(Integer cOrderLineId) {
		this.cOrderLineId = cOrderLineId;
	}

	@Basic
	@Column(name="c_org_id", columnDefinition="INT", nullable=false)
	public Integer getCOrgId() {
		return cOrgId;
	}

	public void setCOrgId(Integer cOrgId) {
		this.cOrgId = cOrgId;
	}

	@Basic
	@Column(nullable=false)
	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getCreatedby() {
		return createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	@Basic
	public Date getUpdated() {
		return updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Basic
	@Column(columnDefinition="INT")
	public Integer getUpdatedby() {
		return updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}
}