package com.freight.model;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.acuity.AcuityCustomizer
 */
@Entity
@Table(name="c_reference_line")
public class CReferenceLine extends com.freight.common.EntityBase {
	private static final long serialVersionUID = 1L;
	private Boolean active;
	private Integer cClientId;
	private Integer cOrgId;
	private Integer cReferenceId;
	private Integer cReferenceLineId;
	private Date created;
	private Integer createdby;
	private String name;
	private Date updated;
	private Integer updatedby;
	private String value;

	public CReferenceLine() {
	}

	public CReferenceLine(Integer cReferenceLineId) {
		this.cReferenceLineId = cReferenceLineId;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Basic
	@Column(name="c_client_id", columnDefinition="INT", nullable=false)
	public Integer getCClientId() {
		return cClientId;
	}

	public void setCClientId(Integer cClientId) {
		this.cClientId = cClientId;
	}

	@Basic
	@Column(name="c_org_id", columnDefinition="INT", nullable=false)
	public Integer getCOrgId() {
		return cOrgId;
	}

	public void setCOrgId(Integer cOrgId) {
		this.cOrgId = cOrgId;
	}

	@Basic
	@Column(name="c_reference_id", columnDefinition="INT", nullable=false)
	public Integer getCReferenceId() {
		return cReferenceId;
	}

	public void setCReferenceId(Integer cReferenceId) {
		this.cReferenceId = cReferenceId;
	}

	@Id
	@Column(name="c_reference_line_id", columnDefinition="INT")
	@TableGenerator(name = "PkGen_115", table = "c_sequence", pkColumnName = "name", pkColumnValue = "C_Reference_Line", valueColumnName = "currentnextsys", allocationSize = 1 )
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "PkGen_115")
	public Integer getCReferenceLineId() {
		return cReferenceLineId;
	}

	public void setCReferenceLineId(Integer cReferenceLineId) {
		this.cReferenceLineId = cReferenceLineId;
	}

	@Basic
	@Column(nullable=false)
	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getCreatedby() {
		return createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	@Basic
	@Column(nullable=false, length=60)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Basic
	public Date getUpdated() {
		return updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Basic
	@Column(columnDefinition="INT")
	public Integer getUpdatedby() {
		return updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}

	@Basic
	@Column(nullable=false, length=20)
	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}
}