package com.freight.model;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.acuity.AcuityCustomizer
 */
@Entity
@Table(name="c_region")
public class CRegion extends com.freight.common.EntityBase {
	private static final long serialVersionUID = 1L;
	private Boolean active;
	private Integer cClientId;
	private Integer cOrgId;
	private Integer cRegionId;
	private Date created;
	private Integer createdby;
	private String name;
	private Integer parentRegionId;
	private Integer regionLevel;
	private Date updated;
	private Integer updatedby;

	public CRegion() {
	}

	public CRegion(Integer cRegionId) {
		this.cRegionId = cRegionId;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Basic
	@Column(name="c_client_id", columnDefinition="INT", nullable=false)
	public Integer getCClientId() {
		return cClientId;
	}

	public void setCClientId(Integer cClientId) {
		this.cClientId = cClientId;
	}

	@Basic
	@Column(name="c_org_id", columnDefinition="INT", nullable=false)
	public Integer getCOrgId() {
		return cOrgId;
	}

	public void setCOrgId(Integer cOrgId) {
		this.cOrgId = cOrgId;
	}

	@Id
	@Column(name="c_region_id", columnDefinition="INT")
	public Integer getCRegionId() {
		return cRegionId;
	}

	public void setCRegionId(Integer cRegionId) {
		this.cRegionId = cRegionId;
	}

	@Basic
	@Column(nullable=false)
	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getCreatedby() {
		return createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	@Basic
	@Column(nullable=false, length=20)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Basic
	@Column(name="parent_region_id", columnDefinition="INT", nullable=false)
	public Integer getParentRegionId() {
		return parentRegionId;
	}

	public void setParentRegionId(Integer parentRegionId) {
		this.parentRegionId = parentRegionId;
	}

	@Basic
	@Column(name="region_level", columnDefinition="INT", nullable=false)
	public Integer getRegionLevel() {
		return regionLevel;
	}

	public void setRegionLevel(Integer regionLevel) {
		this.regionLevel = regionLevel;
	}

	@Basic
	public Date getUpdated() {
		return updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Basic
	@Column(columnDefinition="INT")
	public Integer getUpdatedby() {
		return updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}
}