package com.freight.model;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.acuity.AcuityCustomizer
 */
@Entity
@Table(name="c_sequence")
public class CSequence extends com.freight.common.EntityBase {
	private static final long serialVersionUID = 1L;
	private Integer cClientId;
	private Integer cOrgId;
	private Integer cSequenceId;
	private Date created;
	private Integer createdby;
	private Integer currentnext;
	private Integer currentnextsys;
	private String datecolumn;
	private String decimalpattern;
	private String description;
	private Integer incrementno;
	private Boolean isactive;
	private String isaudited;
	private Boolean isautosequence;
	private Boolean istableid;
	private String name;
	private String prefix;
	private Boolean startnewyear;
	private Integer startno;
	private String suffix;
	private Date updated;
	private Integer updatedby;
	private String vformat;

	public CSequence() {
	}

	public CSequence(Integer cSequenceId) {
		this.cSequenceId = cSequenceId;
	}

	@Basic
	@Column(name="C_CLIENT_ID", columnDefinition="INT", nullable=false)
	public Integer getCClientId() {
		return cClientId;
	}

	public void setCClientId(Integer cClientId) {
		this.cClientId = cClientId;
	}

	@Basic
	@Column(name="C_ORG_ID", columnDefinition="INT", nullable=false)
	public Integer getCOrgId() {
		return cOrgId;
	}

	public void setCOrgId(Integer cOrgId) {
		this.cOrgId = cOrgId;
	}

	@Id
	@Column(name="C_SEQUENCE_ID", columnDefinition="INT")
	public Integer getCSequenceId() {
		return cSequenceId;
	}

	public void setCSequenceId(Integer cSequenceId) {
		this.cSequenceId = cSequenceId;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getCreatedby() {
		return createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getCurrentnext() {
		return currentnext;
	}

	public void setCurrentnext(Integer currentnext) {
		this.currentnext = currentnext;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getCurrentnextsys() {
		return currentnextsys;
	}

	public void setCurrentnextsys(Integer currentnextsys) {
		this.currentnextsys = currentnextsys;
	}

	@Basic
	@Column(length=60)
	public String getDatecolumn() {
		return datecolumn;
	}

	public void setDatecolumn(String datecolumn) {
		this.datecolumn = datecolumn;
	}

	@Basic
	@Column(length=40)
	public String getDecimalpattern() {
		return decimalpattern;
	}

	public void setDecimalpattern(String decimalpattern) {
		this.decimalpattern = decimalpattern;
	}

	@Basic
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getIncrementno() {
		return incrementno;
	}

	public void setIncrementno(Integer incrementno) {
		this.incrementno = incrementno;
	}

	@Basic
	public Boolean isIsactive() {
		return isactive;
	}

	public void setIsactive(Boolean isactive) {
		this.isactive = isactive;
	}

	@Basic
	@Column(length=1)
	public String getIsaudited() {
		return isaudited;
	}

	public void setIsaudited(String isaudited) {
		this.isaudited = isaudited;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isIsautosequence() {
		return isautosequence;
	}

	public void setIsautosequence(Boolean isautosequence) {
		this.isautosequence = isautosequence;
	}

	@Basic
	public Boolean isIstableid() {
		return istableid;
	}

	public void setIstableid(Boolean istableid) {
		this.istableid = istableid;
	}

	@Basic
	@Column(nullable=false, length=60)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Basic
	public String getPrefix() {
		return prefix;
	}

	public void setPrefix(String prefix) {
		this.prefix = prefix;
	}

	@Basic
	public Boolean isStartnewyear() {
		return startnewyear;
	}

	public void setStartnewyear(Boolean startnewyear) {
		this.startnewyear = startnewyear;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getStartno() {
		return startno;
	}

	public void setStartno(Integer startno) {
		this.startno = startno;
	}

	@Basic
	public String getSuffix() {
		return suffix;
	}

	public void setSuffix(String suffix) {
		this.suffix = suffix;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public Date getUpdated() {
		return updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getUpdatedby() {
		return updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}

	@Basic
	@Column(length=40)
	public String getVformat() {
		return vformat;
	}

	public void setVformat(String vformat) {
		this.vformat = vformat;
	}
}