package com.freight.model;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.acuity.AcuityCustomizer
 */
@Entity
@Table(name="c_user")
public class CUser extends com.freight.common.EntityBase {
	private static final long serialVersionUID = 1L;
	private Boolean active;
	private Date birthday;
	private Integer cBpartnerId;
	private Integer cClientId;
	private Integer cOrgId;
	private Integer cUserId;
	private Date created;
	private Integer createdby;
	private String mobile;
	private String name;
	private String password;
	private String phone;
	private Date updated;
	private Integer updatedby;

	public CUser() {
	}

	public CUser(Integer cUserId) {
		this.cUserId = cUserId;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Basic
	@Column(nullable=false)
	@Temporal(TemporalType.DATE)
	public Date getBirthday() {
		return birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Basic
	@Column(name="c_bpartner_id", columnDefinition="INT")
	public Integer getCBpartnerId() {
		return cBpartnerId;
	}

	public void setCBpartnerId(Integer cBpartnerId) {
		this.cBpartnerId = cBpartnerId;
	}

	@Basic
	@Column(name="c_client_id", columnDefinition="INT", nullable=false)
	public Integer getCClientId() {
		return cClientId;
	}

	public void setCClientId(Integer cClientId) {
		this.cClientId = cClientId;
	}

	@Basic
	@Column(name="c_org_id", columnDefinition="INT", nullable=false)
	public Integer getCOrgId() {
		return cOrgId;
	}

	public void setCOrgId(Integer cOrgId) {
		this.cOrgId = cOrgId;
	}

	@Id
	@Column(name="c_user_id", columnDefinition="INT")
	@TableGenerator(name = "PkGen_116", table = "c_sequence", pkColumnName = "name", pkColumnValue = "C_User", valueColumnName = "currentnextsys", allocationSize = 1 )
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "PkGen_116")
	public Integer getCUserId() {
		return cUserId;
	}

	public void setCUserId(Integer cUserId) {
		this.cUserId = cUserId;
	}

	@Basic
	@Column(nullable=false)
	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getCreatedby() {
		return createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	@Basic
	@Column(nullable=false, length=20)
	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Basic
	@Column(nullable=false, length=60)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Basic
	@Column(nullable=false, length=40)
	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Basic
	@Column(length=20)
	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Basic
	public Date getUpdated() {
		return updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Basic
	@Column(columnDefinition="INT")
	public Integer getUpdatedby() {
		return updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}
}