package com.freight.model;

import java.math.*;
import javax.persistence.*;

import com.freight.common.EntityBase;

/**
 * Auto-generated by:
 * org.freight.AdempiereCustomizer
 */
@Entity
@Table(name="c_vehicle")
public class CVehicle extends EntityBase {
	private static final long serialVersionUID = 1L;
	private Integer aDOrgID;
	private Integer cVehicleID;
	private String comment;
	private String contractNo;
	private String dateDepart;
	private String datePromised;
	private String dateScrap;
	private String dateUsing;
	private BigDecimal depreciationCharge;
	private String driver;
	private String driverAddr;
	private Integer driverID;
	private String driverLicenceNo;
	private String driverPhone;
	private String engineNo;
	private Integer entrustMoveID;
	private String insuranceNo;
	private String licenseNo;
	private String limited;
	private BigDecimal mileageCurrent;
	private BigDecimal mileageStart;
	private BigDecimal mileageTerminal;
	private Integer modelType;
	private String name;
	private BigDecimal oilConsumption;
	private String operationNo;
	private String owner;
	private String ownerAddr;
	private Integer ownerID;
	private String ownerPhone;
	private String plateNo;
	private BigDecimal tonnage;
	private String trailerPlateNo;

	public CVehicle() {
	}

	public CVehicle(Integer cVehicleID) {
		this.cVehicleID = cVehicleID;
	}

	@Basic
	@Column(name="ad_org_id", columnDefinition="INT", nullable=false)
	public Integer getADOrgID() {
		return aDOrgID;
	}

	public void setADOrgID(Integer aDOrgID) {
		this.aDOrgID = aDOrgID;
	}

	@Id
	@Column(name="c_vehicle_id", columnDefinition="INT")
	@TableGenerator(name = "PkGen_102", table = "ad_sequence", pkColumnName = "name", pkColumnValue = "C_Vehicle", valueColumnName = "currentnextsys", allocationSize = 1 )
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "PkGen_102")
	public Integer getCVehicleID() {
		return cVehicleID;
	}

	public void setCVehicleID(Integer cVehicleID) {
		this.cVehicleID = cVehicleID;
	}

	@Basic
	@Column(length=100)
	public String getComment() {
		return comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Basic
	@Column(name="contract_no", length=20)
	public String getContractNo() {
		return contractNo;
	}

	public void setContractNo(String contractNo) {
		this.contractNo = contractNo;
	}

	@Basic
	@Column(name="date_depart")
	public String getDateDepart() {
		return dateDepart;
	}

	public void setDateDepart(String dateDepart) {
		this.dateDepart = dateDepart;
	}

	@Basic
	@Column(name="date_promised")
	public String getDatePromised() {
		return datePromised;
	}

	public void setDatePromised(String datePromised) {
		this.datePromised = datePromised;
	}

	@Basic
	@Column(name="date_scrap")
	public String getDateScrap() {
		return dateScrap;
	}

	public void setDateScrap(String dateScrap) {
		this.dateScrap = dateScrap;
	}

	@Basic
	@Column(name="date_using")
	public String getDateUsing() {
		return dateUsing;
	}

	public void setDateUsing(String dateUsing) {
		this.dateUsing = dateUsing;
	}

	@Basic
	@Column(name="depreciation_charge")
	public BigDecimal getDepreciationCharge() {
		return depreciationCharge;
	}

	public void setDepreciationCharge(BigDecimal depreciationCharge) {
		this.depreciationCharge = depreciationCharge;
	}

	@Basic
	@Column(length=20)
	public String getDriver() {
		return driver;
	}

	public void setDriver(String driver) {
		this.driver = driver;
	}

	@Basic
	@Column(name="driver_addr", length=80)
	public String getDriverAddr() {
		return driverAddr;
	}

	public void setDriverAddr(String driverAddr) {
		this.driverAddr = driverAddr;
	}

	@Basic
	@Column(name="driver_id", columnDefinition="INT")
	public Integer getDriverID() {
		return driverID;
	}

	public void setDriverID(Integer driverID) {
		this.driverID = driverID;
	}

	@Basic
	@Column(name="driver_licence_no", length=30)
	public String getDriverLicenceNo() {
		return driverLicenceNo;
	}

	public void setDriverLicenceNo(String driverLicenceNo) {
		this.driverLicenceNo = driverLicenceNo;
	}

	@Basic
	@Column(name="driver_phone", length=20)
	public String getDriverPhone() {
		return driverPhone;
	}

	public void setDriverPhone(String driverPhone) {
		this.driverPhone = driverPhone;
	}

	@Basic
	@Column(name="engine_no", length=20)
	public String getEngineNo() {
		return engineNo;
	}

	public void setEngineNo(String engineNo) {
		this.engineNo = engineNo;
	}

	@Basic
	@Column(name="entrust_move_id", columnDefinition="INT")
	public Integer getEntrustMoveID() {
		return entrustMoveID;
	}

	public void setEntrustMoveID(Integer entrustMoveID) {
		this.entrustMoveID = entrustMoveID;
	}

	@Basic
	@Column(name="insurance_no", length=30)
	public String getInsuranceNo() {
		return insuranceNo;
	}

	public void setInsuranceNo(String insuranceNo) {
		this.insuranceNo = insuranceNo;
	}

	@Basic
	@Column(name="license_no", length=20)
	public String getLicenseNo() {
		return licenseNo;
	}

	public void setLicenseNo(String licenseNo) {
		this.licenseNo = licenseNo;
	}

	@Basic
	public String getLimited() {
		return limited;
	}

	public void setLimited(String limited) {
		this.limited = limited;
	}

	@Basic
	@Column(name="mileage_current")
	public BigDecimal getMileageCurrent() {
		return mileageCurrent;
	}

	public void setMileageCurrent(BigDecimal mileageCurrent) {
		this.mileageCurrent = mileageCurrent;
	}

	@Basic
	@Column(name="mileage_start")
	public BigDecimal getMileageStart() {
		return mileageStart;
	}

	public void setMileageStart(BigDecimal mileageStart) {
		this.mileageStart = mileageStart;
	}

	@Basic
	@Column(name="mileage_terminal")
	public BigDecimal getMileageTerminal() {
		return mileageTerminal;
	}

	public void setMileageTerminal(BigDecimal mileageTerminal) {
		this.mileageTerminal = mileageTerminal;
	}

	@Basic
	@Column(name="model_type", columnDefinition="INT")
	public Integer getModelType() {
		return modelType;
	}

	public void setModelType(Integer modelType) {
		this.modelType = modelType;
	}

	@Basic
	@Column(length=20)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Basic
	@Column(name="oil_consumption")
	public BigDecimal getOilConsumption() {
		return oilConsumption;
	}

	public void setOilConsumption(BigDecimal oilConsumption) {
		this.oilConsumption = oilConsumption;
	}

	@Basic
	@Column(name="operation_no", length=20)
	public String getOperationNo() {
		return operationNo;
	}

	public void setOperationNo(String operationNo) {
		this.operationNo = operationNo;
	}

	@Basic
	@Column(length=20)
	public String getOwner() {
		return owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	@Basic
	@Column(name="owner_addr", length=50)
	public String getOwnerAddr() {
		return ownerAddr;
	}

	public void setOwnerAddr(String ownerAddr) {
		this.ownerAddr = ownerAddr;
	}

	@Basic
	@Column(name="owner_id", columnDefinition="INT")
	public Integer getOwnerID() {
		return ownerID;
	}

	public void setOwnerID(Integer ownerID) {
		this.ownerID = ownerID;
	}

	@Basic
	@Column(name="owner_phone", length=20)
	public String getOwnerPhone() {
		return ownerPhone;
	}

	public void setOwnerPhone(String ownerPhone) {
		this.ownerPhone = ownerPhone;
	}

	@Basic
	@Column(name="plate_no", length=20)
	public String getPlateNo() {
		return plateNo;
	}

	public void setPlateNo(String plateNo) {
		this.plateNo = plateNo;
	}

	@Basic
	public BigDecimal getTonnage() {
		return tonnage;
	}

	public void setTonnage(BigDecimal tonnage) {
		this.tonnage = tonnage;
	}

	@Basic
	@Column(name="trailer_plate_no", length=20)
	public String getTrailerPlateNo() {
		return trailerPlateNo;
	}

	public void setTrailerPlateNo(String trailerPlateNo) {
		this.trailerPlateNo = trailerPlateNo;
	}
}