package com.freight.model;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.acuity.AcuityCustomizer
 */
@Entity
@Table(name="c_warehouse")
public class CWarehouse extends com.freight.common.EntityBase {
	private static final long serialVersionUID = 1L;
	private Boolean active;
	private Integer cClientId;
	private Integer cOrgId;
	private Integer cWarehouseId;
	private Date created;
	private Integer createdby;
	private String description;
	private Boolean isStart;
	private Boolean isTerminal;
	private String name;
	private Date updated;
	private Integer updatedby;

	public CWarehouse() {
	}

	public CWarehouse(Integer cWarehouseId) {
		this.cWarehouseId = cWarehouseId;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Basic
	@Column(name="c_client_id", columnDefinition="INT", nullable=false)
	public Integer getCClientId() {
		return cClientId;
	}

	public void setCClientId(Integer cClientId) {
		this.cClientId = cClientId;
	}

	@Basic
	@Column(name="c_org_id", columnDefinition="INT", nullable=false)
	public Integer getCOrgId() {
		return cOrgId;
	}

	public void setCOrgId(Integer cOrgId) {
		this.cOrgId = cOrgId;
	}

	@Id
	@Column(name="c_warehouse_id", columnDefinition="INT")
	@TableGenerator(name = "PkGen_118", table = "c_sequence", pkColumnName = "name", pkColumnValue = "C_Warehouse", valueColumnName = "currentnextsys", allocationSize = 1 )
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "PkGen_118")
	public Integer getCWarehouseId() {
		return cWarehouseId;
	}

	public void setCWarehouseId(Integer cWarehouseId) {
		this.cWarehouseId = cWarehouseId;
	}

	@Basic
	@Column(nullable=false)
	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getCreatedby() {
		return createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	@Basic
	@Column(length=200)
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Basic
	@Column(name="is_start", nullable=false)
	public Boolean isIsStart() {
		return isStart;
	}

	public void setIsStart(Boolean isStart) {
		this.isStart = isStart;
	}

	@Basic
	@Column(name="is_terminal", nullable=false)
	public Boolean isIsTerminal() {
		return isTerminal;
	}

	public void setIsTerminal(Boolean isTerminal) {
		this.isTerminal = isTerminal;
	}

	@Basic
	@Column(nullable=false, length=45)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Basic
	public Date getUpdated() {
		return updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Basic
	@Column(columnDefinition="INT")
	public Integer getUpdatedby() {
		return updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}
}