/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

//@require @packageOverrides
Ext.Loader.setConfig({
	enabled: true
});

/*******************************************************************************
 * 当前登录用户
 */
var loginUser, imageSizeMap, orderAutoLoadTime, subCommissionBase, resourceUrl, commonTreeNodes;

(function () {
	// var queryCurrentInfo = function() {
	// //Ajax请求当前登录用户信息
	// Ext.Ajax.request({
	// url: '',
	// async: false,
	// success: function(response, opts) {
	// var result = Ext.decode(response.responseText);
	// //设置当前登录用户信息
	// loginUser = result.currentUser;
	// }
	// });
	// };
	// queryCurrentInfo();
	// setInterval(function() {
	// queryCurrentInfo();
	// }, Common.config.UPDATE_INFO_INTERVAL * 1000);
	// Ajax请求当前系统配置信息
	// Ext.Ajax.request({
	// url: '',
	// success: function(response, opts) {
	// var result = Ext.decode(response.responseText);
	// //设置当前系统配置的图片大小信息
	// imageSizeMap = result.imageSizeMap;
	// //设置订单自动刷新时间
	// orderAutoLoadTime = result.orderAutoLoadTime;
	// //公司得到拥金的比例
	// subCommissionBase = result.subCommissionBase;
	// }
	// });
	// 公用菜单项
	commonTreeNodes = [
		{
			text: '运输管理',
			expanded: true,
			children: [
				{
					text: '录入运单',
					leaf: true,
					id: 'EnterOrder',
					action: 'F'
				},
				{
					text: '运单管理',
					leaf: true,
					id: 120,
					action: 'W'
				},
				{
					text: '装车配载',
					leaf: true,
					id: 'MoveAssignment',
					action: 'F'
				},
				{
					text: '车次管理',
					leaf: true,
					id: 'MoveManagment',
					action: 'F'
				},
				{
					text: '发车管理',
					leaf: true,
					id: 117,
					action: 'W'
				},
				{
					text: '库存管理',
					leaf: true,
					id: 115,
					action: 'W'
				}
			]
		},
		{
			text: '异常处理',
			children: [
				{
					text: '异常管理',
					leaf: true,
					id: 1080,
					action: 'W'
				},
				{
					text: '理赔管理',
					leaf: true,
					id: 1089,
					action: 'W'
				}
			]
		},
		{
			text: '报表分析',
			children: [
				{
					text: '库存分析',
					leaf: true,
					id: 1088,
					action: 'W'
				},
				{
					text: '回单分析',
					leaf: true,
					id: 1087,
					action: 'W'
				},
				{
					text: '毛利分析',
					leaf: true,
					id: 1086,
					action: 'W'
				},
				{
					text: '时效分析',
					leaf: true,
					id: 1085,
					action: 'W'
				}
			]
		},
		{
			text: '财务结算',
			children: [
				{
					text: '费用管理',
					leaf: true,
					id: 1084,
					action: 'W'
				},
				{
					text: '应收管理',
					leaf: true,
					id: 1083,
					action: 'W'
				},
				{
					text: '应付管理',
					leaf: true,
					id: 1082,
					action: 'W'
				},
				{
					text: '资金管理',
					leaf: true,
					id: 1081,
					action: 'W'
				}
			]
		},
		{
			text: '基础资料',
			children: [
				{
					text: '车辆管理',
					leaf: true,
					id: 123,
					action: 'W'
				},
				{
					text: '用户管理',
					leaf: true,
					id: 108,
					action: 'W'
				},
				{
					text: '合作伙伴管理',
					leaf: true,
					id: 110,
					action: 'W'
				},
				{
					text: '区域管理',
					leaf: true,
					id: 122,
					action: 'W'
				}
			]
		},
		{
			text: '系统管理',
			children: [
				{
					text: '客户管理',
					leaf: true,
					id: 100,
					action: 'W'
				},
				{
					text: '组织管理',
					leaf: true,
					id: 101,
					action: 'W'
				},
				{
					text: '窗体管理',
					leaf: true,
					id: 104,
					action: 'W'
				},
				{
					text: '字段管理',
					leaf: true,
					id: 105,
					action: 'W'
				}
			]
		}
	];
})();


Ext.define('CurrentUser', {
	singleton: true,
	/**
	 * 当前登录用户对象
	 */
	getCurrentUser: function () {
		if (!Ext.isEmpty(loginUser)) {
			return loginUser;
		}
	},
	/**
	 * 当前登录用户的用户名
	 */
	getRealName: function () {
		if (!Ext.isEmpty(loginUser)) {
			return CurrentUser.getCurrentUser().realName;
		}
	},
	/**
	 * 当前登录用户的用户名
	 */
	getLoginAccount: function () {
		if (!Ext.isEmpty(loginUser)) {
			return CurrentUser.getCurrentUser().loginAccount;
		}
	},
	/**
	 * 当前登录用户类型编码
	 */
	getUserTypeCode: function () {
		if (!Ext.isEmpty(loginUser)) {
			return CurrentUser.getCurrentUser().userType;
		}
	},
	/**
	 * 当前登录用户类型名称
	 */
	getUserTypeName: function () {
		if (!Ext.isEmpty(loginUser)) {
			return DataDictionary.rendererSubmitToDisplay(CurrentUser.getUserTypeCode());
		}
	},
	/**
	 * 当前登录用户菜单
	 */
	getUserMenus: function () {
		return commonTreeNodes;
	}
});

Ext.application({
	models: [ 'InventoryVModel' ],
	stores: [ 'MenuTreeStore' ],
	views: [ 'ADWindowPanel', 'EnterOrder', 'MoveAssignment', 'MoveManagment', 'Viewport' ],
	autoCreateViewport: true,
	appFolder: 'mvc',
	name: 'MyApp',
	launch: Lookup.loadRefList
});
Ext.QuickTips.init();