/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

//@require @packageOverrides
Ext.Loader.setConfig({
	enabled: true
});

/*******************************************************************************
 * 当前登录用户
 */
var loginUser, imageSizeMap, orderAutoLoadTime, subCommissionBase, resourceUrl, commonTreeNodes;

(function () {
	// var queryCurrentInfo = function() {
	// //Ajax请求当前登录用户信息
	// Ext.Ajax.request({
	// url: '',
	// async: false,
	// success: function(response, opts) {
	// var result = Ext.decode(response.responseText);
	// //设置当前登录用户信息
	// loginUser = result.currentUser;
	// }
	// });
	// };
	// queryCurrentInfo();
	// setInterval(function() {
	// queryCurrentInfo();
	// }, Common.config.UPDATE_INFO_INTERVAL * 1000);
	// Ajax请求当前系统配置信息
	// Ext.Ajax.request({
	// url: '',
	// success: function(response, opts) {
	// var result = Ext.decode(response.responseText);
	// //设置当前系统配置的图片大小信息
	// imageSizeMap = result.imageSizeMap;
	// //设置订单自动刷新时间
	// orderAutoLoadTime = result.orderAutoLoadTime;
	// //公司得到拥金的比例
	// subCommissionBase = result.subCommissionBase;
	// }
	// });
	// 公用菜单项
})();


Ext.define('CurrentUser', {
	singleton: true,
	/**
	 * 当前登录用户对象
	 */
	getCurrentUser: function () {
		if (!Ext.isEmpty(loginUser)) {
			return loginUser;
		}
	},
	/**
	 * 当前登录用户的用户名
	 */
	getRealName: function () {
		if (!Ext.isEmpty(loginUser)) {
			return CurrentUser.getCurrentUser().realName;
		}
	},
	/**
	 * 当前登录用户的用户名
	 */
	getLoginAccount: function () {
		if (!Ext.isEmpty(loginUser)) {
			return CurrentUser.getCurrentUser().loginAccount;
		}
	},
	/**
	 * 当前登录用户类型编码
	 */
	getUserTypeCode: function () {
		if (!Ext.isEmpty(loginUser)) {
			return CurrentUser.getCurrentUser().userType;
		}
	},
	/**
	 * 当前登录用户类型名称
	 */
	getUserTypeName: function () {
		if (!Ext.isEmpty(loginUser)) {
			return DataDictionary.rendererSubmitToDisplay(CurrentUser.getUserTypeCode());
		}
	},
	/**
	 * 当前登录用户菜单
	 */
	getUserMenus: function () {
		return commonTreeNodes;
	}
});

Ext.application({
	models: [ 'InventoryVModel', 'MenuModel' ],
	stores: [ ],
	views: [ 'ADWindowPanel', 'EnterOrder', 'MoveAssignment', 'MoveManagment', 'Viewport' ],
	autoCreateViewport: true,
	appFolder: 'mvc',
	name: 'MyApp',
	launch: Lookup.loadRefList
});
Ext.QuickTips.init();